# .bash_profile

# Get the aliases and functions
[ -f $HOME/.bashrc ] && . $HOME/.bashrc

PS1='[ \H ] '"$PS1"

## If X hasn't started, but should, then start it
if [ "$(fgconsole 2>/dev/null || echo -1)" -eq 1 ] && [ $UID -eq 1000 ] && [ -z "$SSH_CLIENT" ] && which startx 2>/dev/null 
    then
    startx
fi

# Normal pager for remote logins
[ -z "$SSH_CLIENT" ] || {
    export PAGER='less -R'
    export MANPAGER='less -R'
}
