[posteo]
outgoing-cred-cmd  = pass email
source-cred-cmd    = pass email
source             = imap://malinfreeborn%40posteo.net@posteo.de
outgoing           = smtp+plain://malinfreeborn%40posteo.net@posteo.de
default            = INBOX
from               = Malin Freeborn <malinfreeborn@posteo.net>
copy-to            = Sent

# [local]
# source             = maildir://~/Mail
# source-cred-cmd    = pass email
# outgoing           = smtp+login://malinfreeborn@posteo.net:yourPassword@posteo.de:143
# from               = Malin Freeborn <malinfreeborn@posteo.net>
# copy-to            = Sent
# check-mail-cmd     = mbsync -a
# check-mail         = 10m
# check-mail-timeout = 20s
# folders-exclude    = Archive,Receipts
