
[general]
editor="$EDITOR"

confirmation=true

mouse-support=false

date-format="2006-01-02 15:04"

date-tody-format="15:04"

date-relative=-1

max-width=800

list-placement="left"

list-split="row"

list-proportion=1

content-proportion=2

notifications-to-hide=[]

quote-reply=false

show-icons=true

short-hints=false

show-filter-phrase=true

show-help=true

stick-to-top=false

show-boosted-user=false

commands-in-new-pane=true

dynamic-timeline-name=true

terminal-title=0

redraw-ui=true

leader-key=""

leader-timeout=1000

[media]
delete-temp-files=true

[media.image]
program="TUT_OS_DEFAULT"

args=""

terminal=false

single=true

reverse=false

[media.video]
program="TUT_OS_DEFAULT"

args=""

terminal=false

single=true

reverse=false

[media.audio]
program="TUT_OS_DEFAULT"

args=""

terminal=false

single=true

reverse=false

[media.link]
program="TUT_OS_DEFAULT"

args=""

terminal=false

[desktop-notification]
followers=false

favorite=false

mention=false

update=false

boost=false

poll=false

posts=false

[open-custom]
[[open-custom.programs]]
program = 'w3m'
terminal = true
hint = "[W]3m"
keys = ["w", "W"]

[open-pattern]
[style]

theme="none"

xrdb-prefix="guess"

background=""

text=""

subtle=""

warning-text=""

text-special-one=""

text-special-two=""

top-bar-background=""

top-bar-text=""

status-bar-background=""

status-bar-text=""

status-bar-view-background=""

status-bar-view-text=""

command-text=""

list-selected-background=""

list-selected-text=""

list-selected-inactive-background=""

list-selected-inactive-text=""

controls-text=""

controls-highlight=""

autocomplete-background=""

autocomplete-text=""

autocomplete-selected-background=""

autocomplete-selected-text=""

button-color-one=""

button-color-two=""

timeline-name-background=""

timeline-name-text=""

[input]

[input.global-down]

keys=["j","J"]

special-keys=["Down"]

[input.global-up]

keys=["k","K"]

special-keys=["Up"]

[input.global-enter]

special-keys=["Enter"]

[input.global-back]

hint="[Esc]"

special-keys=["Esc"]

[input.global-exit]

hint="[Q]uit"

keys=["q","Q"]

[input.main-home]

keys=["g"]

special-keys=["Home"]

[input.main-end]

keys=["G"]

special-keys=["End"]

[input.main-prev-feed]

keys=["h","H"]

special-keys=["Left"]

[input.main-next-feed]

keys=["l","L"]

special-keys=["Right"]

[input.main-prev-pane]

special-keys=["Backtab"]

[input.main-next-pane]

special-keys=["Tab"]

[input.main-next-account]

special-keys=["Ctrl-N"]

[input.main-prev-account]

special-keys=["Ctrl-P"]

[input.main-compose]

keys=["c","C"]

[input.status-avatar]

hint="[A]vatar"

keys=["a","A"]

[input.status-boost]

hint="[B]oost"

keys=["b","B"]

[input.status-edit]

hint="[E]dit"

keys=["e","E"]

[input.status-delete]

hint="[D]elete"

keys=["d","D"]

[input.status-favorite]

hint="[F]avorite"

keys=["f","F"]

[input.status-media]

hint="[M]edia"

keys=["m","M"]

[input.status-links]

hint="[O]pen"

keys=["o","O"]

[input.status-poll]

hint="[P]oll"

keys=["p","P"]

[input.status-reply]

hint="[R]eply"

keys=["r","R"]

[input.status-bookmark]

hint="[S]ave"

hint-alt="Un[S]ave"

keys=["s","S"]

[input.status-thread]

hint="[T]hread"

keys=["t","T"]

[input.status-user]

hint="[U]ser"

keys=["u","U"]

[input.status-view-focus]

hint="[V]iew"

keys=["v","V"]

[input.status-yank]

hint="[Y]ank"

keys=["y","Y"]

[input.status-toggle-cw]

hint="Press [Z] to toggle cw"

keys=["z","Z"]

[input.status-show-filtered]

hint="Press [Z] to view filtered toot"

keys=["z","Z"]

[input.user-avatar]

hint="[A]vatar"

keys=["a","A"]

[input.user-block]

hint="[B]lock"

hint-alt="Un[B]lock"

keys=["b","B"]

[input.user-follow]

hint="[F]ollow"

hint-alt="Un[F]ollow"

keys=["f","F"]

[input.user-follow-request-decide]

hint="Follow [R]equest"

hint-alt="Follow [R]equest"

keys=["r","R"]

[input.user-mute]

hint="[M]ute"

hint-alt="Un[M]ute"

keys=["m","M"]

[input.user-links]

hint="[O]pen"

keys=["o","O"]

[input.user-user]

hint="[U]ser"

keys=["u","U"]

[input.user-view-focus]

hint="[V]iew"

keys=["v","V"]

[input.user-yank]

hint="[Y]ank"

keys=["y","Y"]

[input.list-open-feed]

hint="[O]pen"

keys=["o","O"]

[input.list-user-list]

hint="[U]sers"

keys=["u","U"]

[input.list-user-add]

hint="[A]dd"

keys=["a","A"]

[input.list-user-delete]

hint="[D]elete"

keys=["d","D"]

[input.link-open]

hint="[O]pen"

keys=["o","O"]

[input.link-yank]

hint="[Y]ank"

keys=["y","Y"]

[input.tag-open-feed]

hint="[O]pen"

keys=["o","O"]

[input.tag-follow]

hint="[F]ollow"

hint-alt="Un[F]ollow"

keys=["f","F"]

[input.compose-edit-cw]

hint="[C]W text"

keys=["c","C"]

[input.compose-edit-text]

hint="[E]dit text"

keys=["e","E"]

[input.compose-include-quote]

hint="[I]nclude quote"

keys=["i","I"]

[input.compose-media-focus]

hint="[M]edia"

keys=["m","M"]

[input.compose-post]

hint="[P]ost"

keys=["p","P"]

[input.compose-toggle-content-warning]

hint="[T]oggle CW"

keys=["t","T"]

[input.compose-visibility]

hint="[V]isibility"

keys=["v","V"]

[input.compose-language]

hint="[L]ang"

keys=["l","L"]

[input.compose-poll]

hint="P[O]ll"

keys=["o","O"]

[input.media-delete]

hint="[D]elete"

keys=["d","D"]

[input.media-edit-desc]

hint="[E]dit desc"

keys=["e","E"]

[input.media-add]

hint="[A]dd"

keys=["a","A"]

[input.vote-vote]

hint="[V]ote"

keys=["v","V"]

[input.vote-select]

hint="[Enter] to select"

special-keys=["Enter"]

[input.poll-add]

hint="[A]dd"

keys=["a","A"]

[input.poll-edit]

hint="[E]dit"

keys=["e","E"]

[input.poll-delete]

hint="[D]elete"

keys=["d","D"]

[input.poll-multi-toggle]

hint="Toggle [M]ultiple"

keys=["m","M"]

[input.poll-expiration]

hint="E[X]pires"

keys=["x","X"]

[input.preference-name]

hint="[N]ame"

keys=["n","N"]

[input.preference-visibility]

hint="[V]isibility"

keys=["v","V"]

[input.preference-bio]

hint="[B]io"

keys=["b","B"]

[input.preference-save]

hint="[S]ave"

keys=["s","S"]

[input.preference-fields]

hint="[F]ields"

keys=["f","F"]

[input.preference-fields-add]

hint="[A]dd"

keys=["a","A"]

[input.preference-fields-edit]

hint="[E]dit"

keys=["e","E"]

[input.preference-fields-delete]

hint="[D]elete"

keys=["d","D"]

[input.editor-exit]

hint="[Esc] when done"

special-keys=["Esc"]
