vim9script

# load other files into buffer without having to save
set hidden

# better command-line completion
set wildoptions+=fuzzy
set wildmenu
set incsearch
set laststatus=1

set encoding=utf-8
set fileencoding=utf-8

colorscheme elflord

set cursorline
autocmd BufRead,BufNewFile,TerminalOpen,TermChanged * hi CursorLine cterm=underline ctermbg=none

# stop vi compatibility
set nocompatible

# allow searching in sub directories
set path+=**

set clipboard=unnamedplus
syntax on
set number relativenumber showcmd
# remove empty line indicator
set fillchars=eob:\ ,

# Remove background colour from colourscheme.
# This is repeated at the end.
autocmd BufNew,BufEnter,BufRead,BufNewFile * hi Normal ctermbg=NONE
autocmd BufNew,BufEnter,BufRead,BufNewFile  * hi EndOfBuffer ctermbg=NONE

# change highlights

hi SpellBad ctermbg=None
hi SpellCap ctermbg=None
hi SpellLocal ctermbg=None
hi SpellRare ctermbg=None
hi Special ctermbg=None

set autoindent
set linebreak
set tabstop=4


# Markdown
## Don't mark _underscores as errors
hi link markdownError Normal
hi link texError Normal

set spelllang=en_gb
set complete+=kspell

# auto-fix last spelling mistake on Ctrl+l
inoremap <C-l> <c-g>u<Esc>[s1z=gi<c-g>u

hi clear SpellBad
hi SpellBad cterm=underline
hi SpellCap cterm=underline
hi SpellLocal cterm=underline
hi SpellRare cterm=underline

map Q gq
map mf :e <cfile><Enter>
map gs :split <cfile><Enter>
map gv :vsplit <cfile><Enter>
map ,v :vsp\|ter<Enter>
map ,t :vert terminal <Enter>
map ,T :terminal <Enter>
map ,m :w<Enter> :make <Enter>
map ,M :terminal ++close make <Enter>
map ,p :%s/[^[:print:]]//g<Enter>

# ask about saving instead of just failing
set confirm

# split window navigation
	map <Esc>h <C-w>h 
	map <Esc>j <C-w>j 
	map <Esc>k <C-w>k 
	map <Esc>l <C-w>l 

set splitbelow splitright

# git
map ,g :wa<Enter> :!git add % && git commit -m""<Left>

filetype on
filetype plugin on

hi Normal ctermbg=NONE
hi EndOfBuffer ctermbg=NONE
