#!/bin/sh

set -e

db=~/rec/nb.rec

[ -r "$db" ] || {
    echo need $db
    mkdir -p "$(dirname "$db")"
    cat >> "$db" <<EOF
%rec: note
%doc: unstructured bits of thought
%key: id
%type: id int
%auto: id
%type: date date
%auto: date
%allowed: date head tag url author body path
%type: url rec article
%type: head,path,url line
%type: tag word
%typedef: word regexp /^[a-z]+[0-9]*$/

%rec: article
%doc: Pages from the web and beyond
%key: url
%type: url line

EOF
}

id=$(recsel "$db" -t note -CR id | tail -1)
id="$(( id + 1 ))"

parser="$(command -v html2markdown html2text | head -1)"
graph_format(){
    printf '%s\n' "[ {{id}} {{tag}} ] --> [ {{link_id[$1]}} {{link_tag}} ]"
}

format="# {{head}}

({{id}}) < {{tag[0]}} {{tag[1]}} {{tag[2]}} {{tag[3]}}  > {{link[0]}} {{link[1]}} {{link[2]}} {{link[3]}}

{{body}}

{{url}}

---
"

while getopts 'rblf:p:a:g:k:q:t:u:' OPTION; do
  case "$OPTION" in
    b) #^# -b Make a graph with graph-easy
    for x in $(seq 0 8); do
        recsel -t note "$db" -j link -e "#link_id_ > $(( x - 1 ))"  | recfmt "$(graph_format $x)"
    done  | graph-easy --boxart
    exit 0
    ;;
    p) #^# -p Tag previous note
      id="$(( id - 1 ))"
      for t in $OPTARG; do
        recset --verbose "$db" -t note -n "$id" -f tag -a "$t"
      done
      exit 0
      ;;
    g) #^# -g Get notes
      recsel "$db" -t note -iq "$OPTARG" -p id,tag,link,head | recsel -m 3 | recfmt "$format" | lowdown -stterm
      exit 0
      ;;
    r) #^# -r Random note
      recsel -t note "$db" -e '#tag = 0'
      topic="$(recsel -t note "$db" -m 1 -CP tag | head -1)"
      recsel -t note "$db" -e "tag = '${topic}'" | recfmt "$format" | lowdown -stterm | less -RFi
      exit 0
      ;;
    t) #^# -t "$tag1 $tag2" Long note, no body
      [ -z "$tags" ] && tags="$OPTARG" || tags="$tags $OPTARG"
      ;;
    a) #^# -a Set author
      author="$OPTARG"
      ;;
    l) #^# -l link $id to $id
      shift "$(($OPTIND -1))"
      case "$#" in
        0)
        printf '# '
        recsel "$db" -t note -e "link = ''" | recsel -m1 | recfmt "${format}" | lowdown -tterm
        exit 0
        ;;
        1)
        [ "$1" -gt -1 ] 2>/dev/null || exit "Give me a number"
        recsel "$db" -t note -e "id = ${1}" | recfmt "${format}" | lowdown -tterm
        exit 0
        ;;
        2)
        recset "$db" -t note -e "id = ${1}" -f link -a ${2}
        exit 0
        ;;
        *)
        echo "One link only"
        exit 4
        ;;
      esac
      exit 0
      ;;
    k) #^# -k Set link
      link="$OPTARG"
      ;;
    q) #^# -q Quote
      quote="$OPTARG"
      ;;
    f) #^# -f Note a relevant file
      file="$OPTARG"
      ;;
    u) #^# -u Set a URL
      url="$OPTARG"
      ;;
    ?)
      echo "Usage: "
      echo "$(basename $0) [note]"
      grep -oP '#\^# \K.*' $0
      exit 0
      ;;
  esac
done
shift "$(($OPTIND -1))"

head="$@"

trap cleanup EXIT

cleanup(){
    [ ! -r "$tmp" ] || rm "$tmp"
}

tmp="$(mktemp)"

[ $(( ${#head} * ${#tags} )) -gt 10 ] || {
    echo "$head" > "$tmp"
    echo "$tags" >> "$tmp"
    echo "" >> "$tmp"
    vim "$tmp" -c 'set filetype=markdown' -c "e!"
    head="$(sed -n '1p' "$tmp")" && body="$(sed '1,2d' "$tmp")" && tags="$(sed -n '2p' "$tmp")"
}


[ $(( ${#head} + ${#tags} )) -gt 5 ] || exit 1

recins -t note "$db" -f head -v "$head"

[ -z "$body" ] || recset "$db" -t note -n "$id" -f body -a "$body"

[ -z "$link" ] || recset "$db" -t note -n "$id" -f link -a "$link"

for t in $tags; do
    recset "$db" -t note -n "$id" -f tag -a "$t"
done

########### Author

[ -z "$author" ] || recset "$db" -t note -n "$id" -f author -a "$author"

########### Quote

[ -z "$quote" ] || recset "$db" -t note -n "$id" -f quote -a "$quote"

########### URL

[ -z "$url" ] || {
    recset "$db" -t note -n "$id" -f url -a "$url"
    [ -n "$parser" ] || {
        echo Install html2markdown or html2text
        exit 2
    } \
    && curl -sL "$url" | $parser > "$tmp" \
    && [ "$(wc -l < "$tmp")" -gt 2 ] \
    && $VISUAL "$tmp" \
    && [ "$(wc -w < "$tmp")" -gt  2 ] \
    && recins "$db" -t article -f url -v "$url" -f title -v "$(sed -n 's/# //; 1p' "$tmp")" -f body -v "$(sed '1d' "$tmp")" \
    || echo "No article copied"
}

########### File

[ -z "$file" ] || {
    [ -r "$file" ] && recset "$db" -t note -n "$id" -f file -a "$file" || echo "No such file"
}

recfix "$db"
