#!/bin/bash

d="$1"

n="$2"

b="${3:-0}"

r=0
x=0

while [ $d -gt 0 ]
do
	x=$(( RANDOM % n + 1 ))
	r=$(( r + x ))
	printf "\t%s\n" " $x"
	((d--))
done

[ "$b" -gt "0" ] && printf "\t%s\n" "+$b" || [ "$b" -eq "0" ] || printf "\t%s\n" "$b"

r=$(( r + b ))

figlet " $r" | lolcat

