#!/bin/sh

set -e

recnik=~/.cache/recnik.rec

command -v sk >/dev/null && fuzzy=sk

word="$@"

##########################

check_db(){
    recfix --auto "$recnik" 2>/dev/null || [ -f "$recnik" ] || {
        echo "Making DB"
        echo "%rec: Recnik" >> "$recnik"
        echo "%key: Id" >> "$recnik"
        echo "%type: Id,Count int" >> "$recnik"
        echo "%auto: Id" >> "$recnik"
    }
    entry_count="$(recsel "$recnik" -t Recnik -c)"
}

check_translation(){
    raw_dump="$(trans sr:en  -dump "$word")"
}

find_words(){
    echo "$raw_dump" | grep '^\[' | jq -r ".[1].[0].[1].[]"
}

find_sentence(){
    echo "$raw_dump" | grep '^\[' | jq -r ".[0].[0].[0]"
}

find_definition(){
    definition="$(find_words || find_sentence)" 2>/dev/null
    test "$definition" != "$word" && test -n "$definition" && test "$definition" != ""
}

find_serbian(){
    guessOne="$(echo "$raw_dump" | grep '^\[' | jq -r ".[1].[0].[3]")"
    guessTwo="$(echo "$raw_dump" | grep '^\[' | jq -r ".[1].[0].[2].[0].[1].[0]")"
    new_words="$(printf "$guessOne\n$guessTwo\n$word" | sort | uniq | grep -v null)"
    srb_cmd="$(echo "$new_words" | sed 's/.*/-f Serbian -v "&"/')"
}

remember_definition(){
    cmd="$(echo "$definition" | sed 's/.*/-f English -v "&"/')"
    find_serbian
    eval recins -t Recnik $recnik -f Count -v 0 $cmd $srb_cmd
    recsel -t Recnik $recnik -n "$entry_count" -P "Serbian,English"

}

check_repeats(){
    test "$(recsel -t Recnik $recnik -e "Serbian ~ '${word}'" -c)" -eq 0 || {
        echo "Already have this:"
        recsel -t Recnik $recnik -e "Serbian ~ '${word}'" -CP Serbian
        exit 1
    }
}

get_revise_word(){
    word_id="$(recsel .cache/recnik.rec -t Recnik --sort Count -n 0-3 | recsel -m 1 -P Id)"
    current_word_count="$(recsel .cache/recnik.rec -t Recnik -e "Id = '${word_id}'" -P Count)"
    right_words="$(recsel .cache/recnik.rec -t Recnik -e "Id = '${word_id}'" -CP English)"
    wrong_words="$(recsel .cache/recnik.rec -t Recnik -m 4 -CP English)"
    wordlist="$(printf "$right_words\n$wrong_words\n" | sort | uniq | shuf)"
}

check_answer(){
    RED='\033[0;31m'
    quizword="$(recsel .cache/recnik.rec -t Recnik -e "Id = '${word_id}'" -P Serbian | shuf -n 1)"
    selection="$(echo "$wordlist" | $fuzzy -p "$quizword ??")"
    echo "$right_words" | grep -q "$selection" && printf "\033[1;32m\tДа\n" || printf "\033[1;31mПогрешно\n"
    printf "\t$quizword значи \033[1;33m$right_words\033[0;0m\n\t"
}

increase_score(){
    score=$(( current_word_count + 1 ))
    recset .cache/recnik.rec -t Recnik -e "Id = '${word_id}'" -f Count -s "$score"
    echo score is "$score"
}

decrease_score(){
    score=$(( current_word_count - 1 ))
    recset .cache/recnik.rec -t Recnik -e "Id = '${word_id}'" -f Count -s "$score"
    echo score is "$score"
}


#############################

check_db

test -z "$1" && {
    test "$entry_count" -gt 3 || {
        echo "Треба још рећи"
        exit 1
    }
    get_revise_word
    check_answer && increase_score || decrease_score
} || {
    check_translation
    find_definition || { 
        echo "Што?"
        exit 0
    }
    check_repeats && remember_definition
}

